# Generated by Django 2.1.4 on 2019-02-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
